kind: Deployment
apiVersion: apps/v1
metadata:
  name: acc-demo-app-account
  namespace: acc
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: acc-demo-app-account
    app.kubernetes.io/managed-by: ArgoCD
    app.kubernetes.io/name: acc-demo-app-account
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: acc-demo-app-account
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/instance: acc-demo-app-account
        app.kubernetes.io/managed-by: ArgoCD
        app.kubernetes.io/name: acc-demo-app-account
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
        - resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          lifecycle:
            preStop:
              exec:
                command:
                  - sleep
                  - '5'
          name: acc-demo-app-account
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: >-
            registry.hub.docker.com/sgchub/demo-app-account
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 600
